//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public string id_carrito { get; set; }
        public System.DateTime fecha { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string cod_producto { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
