//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleorden
    {
        public string num_orden { get; set; }
        public string cod_producto { get; set; }
        public int cantidad { get; set; }
        public decimal importe { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual orden orden { get; set; }
    }
}
